name: climexp_numerical_wps
channels:
- conda-forge
- defaults
dependencies:
- pip
#- pywps=4.2
- jinja2
- click
- psutil
# tests
- pytest
- netcdf-fortran 
- gsl
- fortran-compiler 
- pip:
  - -e git+https://github.com/geopython/pywps@master#egg=pywps
